name: ✨ Enhancement
description: New features or enhancements to the website itself.
title: "Add light / dark mode toggle"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping out to improve the Greenwood website!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide a summary of the current state of the website and what you would like updated about it.
      placeholder: The website should have...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional details, links, or resources that may be helpful for consideration of this enhancement.
    validations:
      required: false
